theme = "amberwood"

[editor]
scrolloff = 8
line-number = "relative"
cursorline = true
auto-completion = true
auto-format = false
preview-completion-insert = true
bufferline = "always"
color-modes = true
insert-final-newline = true
auto-pairs = true
end-of-line-diagnostics = "hint"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-modification-indicator",
  "read-only-indicator",
]
center = ["file-name"]
right = [
  "version-control",
  "diagnostics",
  "workspace-diagnostics",
  "position",
  "register",
  "selections",
  "file-encoding",
  "file-line-ending",
  "file-type",
]

[editor.lsp]
enable = true
display-progress-messages = true
auto-signature-help = true
display-inlay-hints = true
snippets = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 60000 # ms

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
skip-levels = 1

[editor.smart-tab]
enable = true
supersede-menu = true

[editor.soft-wrap]
enable = true
max-wrap = 30
max-indent-retain = 8
wrap-at-text-width = true

[editor.inline-diagnostics]
cursor-line = "info"
other-lines = "hint"
max-wrap = 30

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

[keys.insert]
S-tab = "move_parent_node_start"
